In [2]:
import numpy as np # np is an alias

In [3]:
np.__version__

'2.0.1'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lis = [1,2,"bla",'B',True]

In [7]:
# Numpy stores the data in a numpy array
# An array is a container used to store data of same data type

In [10]:
# Numpy is built using C >>  Hence numpy computation is fast
# due to array >> homogeneous data is stored >> numpy array is faster
# homogeneous data >> continuos memory location

In [12]:
MyArray = [1,2,3,4,5]

In [14]:
arr = np.array(MyArray)

In [17]:
type(arr)  # numpy.ndarray >> n dimensional array

numpy.ndarray

In [25]:
l = [1,2,3,4,5,"Max"]
print(np.array(l)) # int data was promoted to string

['1' '2' '3' '4' '5' 'Max']


In [26]:
arr.ndim

1

In [41]:
l2 = [ [1,3,4,5,6],
       [2,3,3,4,5],
       [1,0,1,0,1] ]
arr2 = np.array(l2)

In [42]:
arr2.ndim

2

In [43]:
arr2

array([[1, 3, 4, 5, 6],
       [2, 3, 3, 4, 5],
       [1, 0, 1, 0, 1]])

In [48]:
for i in range(3):
    for j in range(5):
        print(arr2[i][j],end = " ")
    print()
    

1 3 4 5 6 
2 3 3 4 5 
1 0 1 0 1 


In [56]:

Matrix_3x3 = np.matrix( [[1,2,3],
                         [2,1,3],
                         [3,2,1]] )

In [57]:
Matrix_3x3.ndim

2

In [58]:
Matrix_3x3

matrix([[1, 2, 3],
        [2, 1, 3],
        [3, 2, 1]])

In [60]:
# 3 Dimensional Matrix does not exist
# It must be 2 dimensional

In [66]:
ThreeD_arr = np.array(( [[[1,2,3],
                          [2,1,3],
                          [3,2,1]]]))

In [67]:
ThreeD_arr.ndim

3

In [68]:
# Three Dim--> [[[ ]]]
# Two dim --> [[ ]]
# One dim --> [ ]

In [74]:
lisst = [[1,2,3],
            [2,1,3],
                [3,2,1]]

In [75]:
my_arr = np.asarray(lisst)

In [76]:
np.asanyarray(lisst)

array([[1, 2, 3],
       [2, 1, 3],
       [3, 2, 1]])

In [77]:
np.asanyarray(my_arr)

array([[1, 2, 3],
       [2, 1, 3],
       [3, 2, 1]])

In [79]:
# asanyarray will convert the input to an ndarray, but pass ndarray subclass 
# if something is already an array or its subclass like matrux then it just 
# lets it pass through

In [82]:
t = ([1,2,3],
     [4,5,6])

In [85]:
arr = np.array(t)

In [89]:
arr[0][1] = 0
arr[0][0] = 0

In [91]:
for i in range(2):
    for j in range(3):
        print(arr[i][j], end = " ")
    print()

0 0 3 
4 5 6 


In [92]:
# shallow copy >> change in one array will lead to change in another

In [93]:
b = arr.copy()

In [96]:
b[0][0] = 100
b[0][1] = 100

In [97]:
for i in range(2):
    for j in range(3):
        print(b[i][j], end = " ")
    print()

100 100 3 
4 5 6 


In [98]:
# To create an array >> np.array, np.asarray, np.asanyarray