In [43]:
import numpy as np

In [44]:
# Q1. 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [45]:
Array_3x3 = np.random.randint(1,101,size =(3,3))
Array_3x3

array([[ 11,  31,  30],
       [ 24,  85,  11],
       [100,  41,   9]], dtype=int32)

In [46]:
Array_3x3.T  # Transposing to interchange rows and columns

array([[ 11,  24, 100],
       [ 31,  85,  41],
       [ 30,  11,   9]], dtype=int32)

In [47]:
# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [48]:
Array_of_ten = np.random.randint(1,11, size = (1,10))
Array_of_ten

array([[ 2,  4,  8,  1,  3,  1, 10,  4,  3,  6]], dtype=int32)

In [49]:
Array_of_ten.reshape(2,5)

array([[ 2,  4,  8,  1,  3],
       [ 1, 10,  4,  3,  6]], dtype=int32)

In [50]:
Array_of_ten.reshape(5,2)

array([[ 2,  4],
       [ 8,  1],
       [ 3,  1],
       [10,  4],
       [ 3,  6]], dtype=int32)

In [51]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [52]:
Array_4x4 = np.random.rand(4,4)
Array_4x4

array([[0.62506855, 0.11989201, 0.69697393, 0.97244997],
       [0.83373929, 0.04367657, 0.34421703, 0.37095015],
       [0.79914345, 0.93814374, 0.68958832, 0.695045  ],
       [0.09211869, 0.32784729, 0.87553422, 0.56625348]])

In [53]:
Array_6x6 = np.zeros((6,6))
Array_6x6[1:5,1:5] = Array_4x4 # Assigning those random values to the core
print(Array_6x6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.62506855 0.11989201 0.69697393 0.97244997 0.        ]
 [0.         0.83373929 0.04367657 0.34421703 0.37095015 0.        ]
 [0.         0.79914345 0.93814374 0.68958832 0.695045   0.        ]
 [0.         0.09211869 0.32784729 0.87553422 0.56625348 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [54]:
# Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [61]:
numpy_arr = np.arange(10,61,5)
numpy_arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [62]:
# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

In [85]:
string_arr = np.array(['python', 'numpy', 'pandas'])

In [88]:
upper_string = np.char.upper(string_arr)
upper_string

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [89]:
lower_string = np.char.lower(string_arr)
lower_string

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [91]:
title_string = np.char.title(string_arr)
title_string

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [92]:
swapcase_string = np.char.swapcase(string_arr)
swapcase_string

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')