In [4]:
import numpy as np

In [5]:
# Q1. 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [6]:
Array_3x3 = np.random.randint(1,101,size =(3,3))
Array_3x3

array([[70, 24, 92],
       [10, 88, 62],
       [17, 65, 47]], dtype=int32)

In [7]:
Array_3x3.T  # Transposing to interchange rows and columns

array([[70, 10, 17],
       [24, 88, 65],
       [92, 62, 47]], dtype=int32)

In [8]:
# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [9]:
Array_of_ten = np.random.randint(1,11, size = (1,10))
Array_of_ten

array([[ 7,  3, 10, 10, 10,  3,  9,  5,  3,  7]], dtype=int32)

In [10]:
Array_of_ten.reshape(2,5)

array([[ 7,  3, 10, 10, 10],
       [ 3,  9,  5,  3,  7]], dtype=int32)

In [11]:
Array_of_ten.reshape(5,2)

array([[ 7,  3],
       [10, 10],
       [10,  3],
       [ 9,  5],
       [ 3,  7]], dtype=int32)

In [12]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [13]:
Array_4x4 = np.random.rand(4,4)
Array_4x4

array([[0.45345993, 0.97402679, 0.20047662, 0.29912414],
       [0.85078411, 0.20354955, 0.76682907, 0.25848838],
       [0.17796468, 0.54068521, 0.26055305, 0.51988176],
       [0.4239058 , 0.59302672, 0.10476009, 0.38986441]])

In [14]:
Array_6x6 = np.zeros((6,6))
Array_6x6[1:5,1:5] = Array_4x4 # Assigning those random values to the core
print(Array_6x6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.45345993 0.97402679 0.20047662 0.29912414 0.        ]
 [0.         0.85078411 0.20354955 0.76682907 0.25848838 0.        ]
 [0.         0.17796468 0.54068521 0.26055305 0.51988176 0.        ]
 [0.         0.4239058  0.59302672 0.10476009 0.38986441 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [15]:
# Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [16]:
numpy_arr = np.arange(10,61,5)
numpy_arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [17]:
# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

In [18]:
string_arr = np.array(['python', 'numpy', 'pandas'])

In [19]:
upper_string = np.char.upper(string_arr)
upper_string

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [20]:
lower_string = np.char.lower(string_arr)
lower_string

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [21]:
title_string = np.char.title(string_arr)
title_string

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [22]:
swapcase_string = np.char.swapcase(string_arr)
swapcase_string

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [23]:
# Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [24]:
arr_of_wrds = np.array(['MaxineMinx', 'DeborahMorgan', 'LucasHood'])
spaced_wrds = np.array([' '.join(list(wrd)) for wrd in arr_of_wrds])
spaced_wrds

array(['M a x i n e M i n x', 'D e b o r a h M o r g a n',
       'L u c a s H o o d'], dtype='<U25')

In [25]:
# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [26]:
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[1, 3, 2],
       [8, 1, 6],
       [5, 3, 7]], dtype=int32)

In [27]:
arr2 = np.random.randint(10,20,(3,3))
arr2

array([[10, 18, 18],
       [16, 13, 11],
       [18, 12, 13]], dtype=int32)

In [28]:
arr1 + arr2

array([[11, 21, 20],
       [24, 14, 17],
       [23, 15, 20]], dtype=int32)

In [29]:
arr2 - arr1

array([[ 9, 15, 16],
       [ 8, 12,  5],
       [13,  9,  6]], dtype=int32)

In [30]:
arr1 * arr2

array([[ 10,  54,  36],
       [128,  13,  66],
       [ 90,  36,  91]], dtype=int32)

In [31]:
arr2 / arr1

array([[10.        ,  6.        ,  9.        ],
       [ 2.        , 13.        ,  1.83333333],
       [ 3.6       ,  4.        ,  1.85714286]])

In [32]:
# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [33]:
matrix_5x5 = np.eye(5,5, dtype = int)

In [34]:
diagonal_elements = np.diag(matrix_5x5)
diagonal_elements

array([1, 1, 1, 1, 1])

In [35]:
# Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.

In [81]:
random_integers = np.random.randint(0, 1001, size=100)


def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


prime_numbers = [num for num in random_integers if is_prime(num)]

print(prime_numbers)


[np.int32(677), np.int32(193), np.int32(463), np.int32(101), np.int32(283), np.int32(547), np.int32(733), np.int32(457), np.int32(479), np.int32(563), np.int32(349), np.int32(733), np.int32(457)]


In [41]:
# Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.

In [78]:
Temps_for_Feb = np.random.randint(20,26,size = 28)
Temps_for_Feb

array([20, 24, 23, 21, 24, 23, 20, 22, 23, 20, 21, 25, 21, 24, 21, 24, 24,
       21, 21, 24, 20, 21, 23, 23, 21, 25, 21, 22], dtype=int32)

In [79]:
weeks = Temps_for_Feb.reshape(4,7)
weeks

array([[20, 24, 23, 21, 24, 23, 20],
       [22, 23, 20, 21, 25, 21, 24],
       [21, 24, 24, 21, 21, 24, 20],
       [21, 23, 23, 21, 25, 21, 22]], dtype=int32)

In [80]:
weekly_averages = np.mean(weeks, axis=1)
print('Weekly Temperatures: ')
for temp in weekly_averages:
    print(temp)

Weekly Temperatures: 
22.142857142857142
22.285714285714285
22.142857142857142
22.285714285714285
